name: Debug Build

on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate premake5 project
        run: premake5 vs2019
        shell: bash

      - name: Build 32bit and 64bit debug executables
        run: |
          msbuild /p:Configuration=Debug /p:Platform=x64 Injector.sln
          msbuild /p:Configuration=Debug /p:Platform=Win32 Injector.sln

      - name: Debug Build
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            bin/Debug/*/*.exe
            bin/Debug/*/*.map
            bin/Debug/*/*.pdb
